FROM coreyhanson/docker-ubuntu:cuda9-rt as compile
LABEL maintainer "Corey Ryan Hanson"

#Installs git and downloads from repository.
RUN export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get install --no-install-recommends -y \
        git \
        ca-certificates && \
    rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/golemfactory/golem.git && \
    cd golem && \
    git checkout 26d0347dea08a86d4404526458ab3b542734bbd4

#Installs dependencies.
RUN export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get install -y \
        sudo \
        openssl \
        python3-dev \
        libffi-dev \
        pkg-config \
        libjpeg-dev \
        libopenexr-dev \
        libssl-dev \
        autoconf \
        libgmp-dev \
        libfreeimage-dev \
        libtool \
        python3-netifaces \
        python3-psutil \
        build-essential \
        python3-pip \
        libyaml-dev \
        mock \
        libfreeimage3 \
        wget && \
    rm -rf /var/lib/apt/lists/*

#Builds EverGreenCoin wallet.
RUN pip3 install --upgrade pip
RUN cd golem && \
    pip3 install -r requirements.txt
RUN cd golem && \
    python3 setup.py develop --prefix=$HOME/.local
RUN cd golem && \
    pip3 install pytest pycodestyle freezegun
